### ISSUE TITLE
Que me usas mi api key de google maps gato 😂😂

### ISSUE THREAD

**Issue by segundofarina** [DonosoNaumczuk/skore#88]
https://github.com/DonosoNaumczuk/skore/blob/46e6473d8c2370c755f8f1c98e503dccca3aafbb/webapp/src/main/webapp/WEB-INF/jsp/createMatch.jsp#L112

**Comment by donosonaumczuk** [comment]
~Jajajaja perdón, me robé una inspeccionando un tp random de pawserver para probar y nunca generé la mía.~ La minamos, fue casualidad 👀
